/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingAndPackagingRouteImport } from './routes/shipping-and-packaging'
import { Route as PaymentAndDeliveryRouteImport } from './routes/payment-and-delivery'
import { Route as OrderTrackingRouteImport } from './routes/order-tracking'
import { Route as DeliveryTimeRouteImport } from './routes/delivery-time'
import { Route as DeliveryMethodRouteImport } from './routes/delivery-method'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingAndPackagingRoute = ShippingAndPackagingRouteImport.update({
  id: '/shipping-and-packaging',
  path: '/shipping-and-packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentAndDeliveryRoute = PaymentAndDeliveryRouteImport.update({
  id: '/payment-and-delivery',
  path: '/payment-and-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingRoute = OrderTrackingRouteImport.update({
  id: '/order-tracking',
  path: '/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryTimeRoute = DeliveryTimeRouteImport.update({
  id: '/delivery-time',
  path: '/delivery-time',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryMethodRoute = DeliveryMethodRouteImport.update({
  id: '/delivery-method',
  path: '/delivery-method',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery-method': typeof DeliveryMethodRoute
  '/delivery-time': typeof DeliveryTimeRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/payment-and-delivery': typeof PaymentAndDeliveryRoute
  '/shipping-and-packaging': typeof ShippingAndPackagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery-method': typeof DeliveryMethodRoute
  '/delivery-time': typeof DeliveryTimeRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/payment-and-delivery': typeof PaymentAndDeliveryRoute
  '/shipping-and-packaging': typeof ShippingAndPackagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery-method': typeof DeliveryMethodRoute
  '/delivery-time': typeof DeliveryTimeRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/payment-and-delivery': typeof PaymentAndDeliveryRoute
  '/shipping-and-packaging': typeof ShippingAndPackagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery-method'
    | '/delivery-time'
    | '/order-tracking'
    | '/payment-and-delivery'
    | '/shipping-and-packaging'
    | '/sitemap.xml'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery-method'
    | '/delivery-time'
    | '/order-tracking'
    | '/payment-and-delivery'
    | '/shipping-and-packaging'
    | '/sitemap.xml'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery-method'
    | '/delivery-time'
    | '/order-tracking'
    | '/payment-and-delivery'
    | '/shipping-and-packaging'
    | '/sitemap.xml'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryMethodRoute: typeof DeliveryMethodRoute
  DeliveryTimeRoute: typeof DeliveryTimeRoute
  OrderTrackingRoute: typeof OrderTrackingRoute
  PaymentAndDeliveryRoute: typeof PaymentAndDeliveryRoute
  ShippingAndPackagingRoute: typeof ShippingAndPackagingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-and-packaging': {
      id: '/shipping-and-packaging'
      path: '/shipping-and-packaging'
      fullPath: '/shipping-and-packaging'
      preLoaderRoute: typeof ShippingAndPackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-and-delivery': {
      id: '/payment-and-delivery'
      path: '/payment-and-delivery'
      fullPath: '/payment-and-delivery'
      preLoaderRoute: typeof PaymentAndDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-tracking': {
      id: '/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof OrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-time': {
      id: '/delivery-time'
      path: '/delivery-time'
      fullPath: '/delivery-time'
      preLoaderRoute: typeof DeliveryTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-method': {
      id: '/delivery-method'
      path: '/delivery-method'
      fullPath: '/delivery-method'
      preLoaderRoute: typeof DeliveryMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryMethodRoute: DeliveryMethodRoute,
  DeliveryTimeRoute: DeliveryTimeRoute,
  OrderTrackingRoute: OrderTrackingRoute,
  PaymentAndDeliveryRoute: PaymentAndDeliveryRoute,
  ShippingAndPackagingRoute: ShippingAndPackagingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
